In [59]:
%reload_ext autoreload
%autoreload 2
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from vivarium import InteractiveContext

In [60]:
!cat ../src/vivarium_nih_moud/model_specifications/model_spec.yaml

components:
    vivarium_public_health.population:
        - BasePopulation()
        - Mortality()
    vivarium_nih_moud.components:
        - conditions.moud_model()
        - locations.quarters_model()
        - locations.quarters_risk()
        - locations.SimpleRiskEffect('quarters_risk',
                'oud_consistent_to_on_treatment_for_oud_consistent.transition_rate')
    vivarium_public_health.results:
        - ResultsStratifier()
        - DisabilityObserver()
        - DiseaseObserver('oud_consistent')
        - DiseaseObserver('quarters')
        - MortalityObserver()

configuration:
    input_data:
        input_draw_number: 0
        artifact_path: /home/abie/vivarium_nih_moud/washington.hdf
        # artifact_path: /mnt/team/simulation_science/pub/training/abie/artifacts/washington.hdf

    interpolation:
        order: 0
        extrapolate: True
    randomness:
        map_size: 1_000_000
        key_columns: ['entrance_time', 'age']
        random_seed: 4344
        additional_seed: 169
    time:
        start:
            year: 2019
            month: 1
            day: 1
        end:
            year: 2040
            month: 1
            day: 1
        step_size: 182 # Days
    population:
        population_size: 100_000
        initialization_age_min: 0
        initialization_age_max: 50
        untracking_age: 100
    oud_consistent:
        exposure: 0.016, # HACK: this should not be used, nor necessary
        state_to_risk_category_map:
            oud_consistent: cat1
            susceptible_to_oud_consistent: cat2
            on_treatment_for_oud_consistent : cat2
    quarters:
        state_to_risk_category_map:
            unhoused: cat1
            incarcerated: cat2
            housed : cat3


    stratification:
        default:
            - 'age_group'
            - 'sex'
            - 'current_year'
        # disability:
        #     include:
        #     exclude:
        # mortality:
        #     include:
        #     exclude:
        oud_consistent:
            include:
                - 'quarters'
        quarters:
            include:
                - 'oud_consistent'

In [61]:
sim = InteractiveContext('../src/vivarium_nih_moud/model_specifications/model_spec.yaml')

2025-05-05 17:16:34.991 | INFO     | simulation_4-artifact_manager:77 - Running simulation from artifact located at /home/abie/vivarium_nih_moud/washington.hdf.
2025-05-05 17:16:34.992 | INFO     | simulation_4-artifact_manager:78 - Artifact base filter terms are ['draw == 0'].
2025-05-05 17:16:34.994 | INFO     | simulation_4-artifact_manager:79 - Artifact additional filter terms are None.

/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium_public_health/population/data_transformations.py:57: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  .apply(lambda sub_pop: sub_pop[["value"]] / sub_pop["value"].sum())
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium_public_health/population/data_transformations.py:64: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  .apply(lambda sub_pop: sub_pop[["value"]] / sub_pop["value"].sum())
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium_public_health/population/data_transformations.py:71: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  .apply(lambda sub_pop: sub_pop[["value"]] / sub_pop["value"].sum())
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))

2025-05-05 17:16:36.856 | WARNING  | simulation_4-resource_manager:176 - Resource stream.oud_consistent_initial_states is not produced by any component but is needed to compute (column.oud_consistent).
2025-05-05 17:16:36.857 | WARNING  | simulation_4-resource_manager:176 - Resource stream.quarters_initial_states is not produced by any component but is needed to compute (column.quarters).
2025-05-05 17:16:36.857 | WARNING  | simulation_4-resource_manager:176 - Resource column.quarters_risk is not produced by any component but is needed to compute (value_modifier.oud_consistent_to_on_treatment_for_oud_consistent.transition_rate.1.simple_risk_effect.oud_consistent_to_on_treatment_for_oud_consistent.transition_rate.apply_risk_effect).

/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(

In [62]:
pop0 = sim.get_population()
pop0

,tracked,location,sex,age,entrance_time,alive,exit_time,cause_of_death,years_of_life_lost,oud_consistent,...,on_treatment_for_oud_consistent_event_count,on_treatment_for_oud_consistent_event_time,previous_oud_consistent,housed_event_count,housed_event_time,unhoused_event_count,unhoused_event_time,incarcerated_event_count,incarcerated_event_time,previous_quarters
0,True,Washington,Female,16.939163,2018-07-03,alive,NaT,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,0,NaT,0,NaT,0,NaT,housed
1,True,Washington,Female,39.958889,2018-07-03,alive,NaT,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,0,NaT,0,NaT,0,NaT,housed
2,True,Washington,Male,21.926816,2018-07-03,alive,NaT,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,0,NaT,0,NaT,0,NaT,housed
3,True,Washington,Female,4.568871,2018-07-03,alive,NaT,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,0,NaT,0,NaT,0,NaT,housed
4,True,Washington,Female,34.515565,2018-07-03,alive,NaT,not_dead,0.0,oud_consistent,...,0,NaT,oud_consistent,0,NaT,0,NaT,0,NaT,housed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,True,Washington,Female,26.810172,2018-07-03,alive,NaT,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,0,NaT,0,NaT,0,NaT,housed
99996,True,Washington,Female,4.808079,2018-07-03,alive,NaT,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,0,NaT,0,NaT,0,NaT,housed
99997,True,Washington,Male,33.478481,2018-07-03,alive,NaT,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,0,NaT,0,NaT,0,NaT,housed
99998,True,Washington,Female,2.588977,2018-07-03,alive,NaT,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,0,NaT,0,NaT,0,NaT,housed
99999,True,Washington,Male,37.052429,2018-07-03,alive,NaT,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,0,NaT,0,NaT,0,NaT,housed

In [63]:
pop0.oud_consistent.value_counts()

susceptible_to_oud_consistent      97584
oud_consistent                      1975
on_treatment_for_oud_consistent      441
Name: oud_consistent, dtype: int64

In [64]:
pop0.quarters.value_counts()

housed    100000
Name: quarters, dtype: int64

In [65]:
sim.step()

/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(

In [66]:
pop1 = sim.get_population()

In [67]:
pop1.oud_consistent.value_counts()

susceptible_to_oud_consistent      97594
oud_consistent                      1830
on_treatment_for_oud_consistent      576
Name: oud_consistent, dtype: int64

In [68]:
pop1.quarters.value_counts()

housed          91280
incarcerated     4541
unhoused         4179
Name: quarters, dtype: int64

In [69]:
pd.crosstab(pop0.oud_consistent, pop0.quarters, margins=True)

quarters                         housed     All
oud_consistent
on_treatment_for_oud_consistent     441     441
oud_consistent                     1975    1975
susceptible_to_oud_consistent     97584   97584
All                              100000  100000

In [ ]:
np.round(100*pd.crosstab(pop1.oud_consistent, pop1.quarters, margins=True, normalize='index'), 1)

quarters                         housed  incarcerated  unhoused
oud_consistent
on_treatment_for_oud_consistent    91.1           4.9       4.0
oud_consistent                     90.7           4.6       4.7
susceptible_to_oud_consistent      91.3           4.5       4.2
All                                91.3           4.5       4.2

In [83]:
np.round(100*pd.crosstab(pop1.quarters, pop1.oud_consistent, margins=True, normalize='index'), 1)

oud_consistent,on_treatment_for_oud_consistent,oud_consistent,susceptible_to_oud_consistent
quarters,,,
housed,0.6,1.8,97.6
incarcerated,0.6,1.9,97.5
unhoused,0.6,2.1,97.4
All,0.6,1.8,97.6

# Goal: induce corelation between quarters and oud state

Approach: follow pattern similar to the Risk and RiskEffect models.

In [71]:
sim.step()

/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(

In [72]:
pop2 = sim.get_population()

In [73]:
t = pd.concat([pop0, pop1, pop2], axis=1).filter(like='quarters')
t[t.iloc[:, 2] != 'housed']

,quarters,previous_quarters,quarters,previous_quarters,quarters,previous_quarters
3,housed,housed,incarcerated,housed,unhoused,incarcerated
20,housed,housed,unhoused,housed,incarcerated,unhoused
23,housed,housed,incarcerated,housed,incarcerated,incarcerated
33,housed,housed,incarcerated,housed,housed,incarcerated
48,housed,housed,unhoused,housed,unhoused,unhoused
...,...,...,...,...,...,...
99907,housed,housed,unhoused,housed,incarcerated,unhoused
99924,housed,housed,incarcerated,housed,unhoused,incarcerated
99952,housed,housed,unhoused,housed,incarcerated,unhoused
99979,housed,housed,incarcerated,housed,incarcerated,incarcerated
99984,housed,housed,unhoused,housed,unhoused,unhoused

In [74]:
[x for x in sim.list_values() if 'expo' in x]

['quarters_risk.exposure']

In [75]:
# %cd /home/abie/vivarium_results/washington/2025_05_05_12_20_15/results
# !ls -halt

In [76]:
# pd.read_parquet('deaths.parquet').sort_values('value', ascending=False)

In [77]:
# pd.read_parquet('ylls.parquet').sort_values('value', ascending=False)

In [78]:
# pd.read_parquet('transition_count_oud_consistent.parquet').sort_values('value')

In [79]:
# pd.read_parquet('transition_count_quarters.parquet').sort_values('value')

In [80]:
# pd.read_parquet('person_time_quarters.parquet').sort_values('value')

In [81]:
# pd.read_parquet('person_time_oud_consistent.parquet').sort_values('value')

In [82]:
# pd.read_parquet('ylds.parquet').sort_values('value')