In [1]:
%reload_ext autoreload
%autoreload 2
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from vivarium import InteractiveContext

In [2]:
!cat ../src/vivarium_nih_moud/model_specifications/model_spec.yaml

components:
    vivarium_public_health.population:
        - BasePopulation()
        - Mortality()
    vivarium_nih_moud.components:
        - conditions.moud_model()
        - locations.quarters_model()
        - locations.quarters_risk()
        - locations.SimpleRiskEffect('quarters_risk',
                'oud_consistent_to_on_treatment_for_oud_consistent.transition_rate')
    vivarium_public_health.results:
        - ResultsStratifier()
        - DisabilityObserver()
        - DiseaseObserver('oud_consistent')
        - DiseaseObserver('quarters')
        - MortalityObserver()

configuration:
    input_data:
        input_draw_number: 0
        artifact_path: /home/abie/vivarium_nih_moud/washington.hdf
        # artifact_path: /mnt/team/simulation_science/pub/training/abie/artifacts/washington.hdf

    interpolation:
        order: 0
        extrapolate: True
    randomness:
        map_size: 1_000_000
        key_columns: ['entrance_time', 'age']
        random_seed: 4344
        additional_seed: 169
    time:
        start:
            year: 2019
            month: 1
            day: 1
        end:
            year: 2020
            month: 1
            day: 1
        step_size: 1 # Days
    population:
        population_size: 100_000
        initialization_age_min: 0
        initialization_age_max: 50
        untracking_age: 100
    oud_consistent:
        exposure: 0.016, # HACK: this should not be used, nor necessary
        state_to_risk_category_map:
            oud_consistent: cat1
            susceptible_to_oud_consistent: cat2
            on_treatment_for_oud_consistent : cat2
    quarters:
        state_to_risk_category_map:
            unhoused: cat1
            incarcerated: cat2
            housed : cat3


    stratification:
        default:
            - 'age_group'
            - 'sex'
            - 'current_year'
        # disability:
        #     include:
        #     exclude:
        # mortality:
        #     include:
        #     exclude:
        oud_consistent:
            include:
                - 'quarters'
        quarters:
            include:
                - 'oud_consistent'

In [3]:
sim = InteractiveContext('../src/vivarium_nih_moud/model_specifications/model_spec.yaml')

2025-05-07 14:06:35.079 | INFO     | simulation_1-artifact_manager:77 - Running simulation from artifact located at /home/abie/vivarium_nih_moud/washington.hdf.
2025-05-07 14:06:35.080 | INFO     | simulation_1-artifact_manager:78 - Artifact base filter terms are ['draw == 0'].
2025-05-07 14:06:35.081 | INFO     | simulation_1-artifact_manager:79 - Artifact additional filter terms are None.

/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium_public_health/population/data_transformations.py:57: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  .apply(lambda sub_pop: sub_pop[["value"]] / sub_pop["value"].sum())
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium_public_health/population/data_transformations.py:64: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  .apply(lambda sub_pop: sub_pop[["value"]] / sub_pop["value"].sum())
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium_public_health/population/data_transformations.py:71: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  .apply(lambda sub_pop: sub_pop[["value"]] / sub_pop["value"].sum())
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))

2025-05-07 14:06:37.185 | WARNING  | simulation_1-resource_manager:176 - Resource stream.oud_consistent_initial_states is not produced by any component but is needed to compute (column.oud_consistent).
2025-05-07 14:06:37.186 | WARNING  | simulation_1-resource_manager:176 - Resource stream.quarters_initial_states is not produced by any component but is needed to compute (column.quarters).
2025-05-07 14:06:37.187 | WARNING  | simulation_1-resource_manager:176 - Resource column.quarters_risk is not produced by any component but is needed to compute (value_modifier.oud_consistent_to_on_treatment_for_oud_consistent.transition_rate.1.simple_risk_effect.oud_consistent_to_on_treatment_for_oud_consistent.transition_rate.apply_risk_effect).

/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:72: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(self.data.groupby(list(self.categorical_parameters)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:240: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(data.groupby(list(other_params)))
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(

In [4]:
pop0 = sim.get_population()
pop0

,tracked,age,exit_time,sex,alive,entrance_time,location,cause_of_death,years_of_life_lost,oud_consistent,...,on_treatment_for_oud_consistent_event_count,on_treatment_for_oud_consistent_event_time,previous_oud_consistent,housed_event_time,housed_event_count,unhoused_event_time,unhoused_event_count,incarcerated_event_count,incarcerated_event_time,previous_quarters
0,True,12.191298,NaT,Male,alive,2018-12-31,Washington,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,NaT,0,NaT,0,0,NaT,housed
1,True,25.751698,NaT,Male,alive,2018-12-31,Washington,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,NaT,0,NaT,0,0,NaT,housed
2,True,48.324099,NaT,Female,alive,2018-12-31,Washington,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,NaT,0,NaT,0,0,NaT,housed
3,True,16.939526,NaT,Male,alive,2018-12-31,Washington,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,NaT,0,NaT,0,0,NaT,housed
4,True,16.180101,NaT,Male,alive,2018-12-31,Washington,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,NaT,0,NaT,0,0,NaT,housed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,True,30.616629,NaT,Female,alive,2018-12-31,Washington,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,NaT,0,NaT,0,0,NaT,housed
99996,True,6.068772,NaT,Female,alive,2018-12-31,Washington,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,NaT,0,NaT,0,0,NaT,housed
99997,True,18.512693,NaT,Female,alive,2018-12-31,Washington,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,NaT,0,NaT,0,0,NaT,housed
99998,True,14.626487,NaT,Male,alive,2018-12-31,Washington,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,NaT,0,NaT,0,0,NaT,housed
99999,True,31.308821,NaT,Female,alive,2018-12-31,Washington,not_dead,0.0,susceptible_to_oud_consistent,...,0,NaT,susceptible_to_oud_consistent,NaT,0,NaT,0,0,NaT,housed

In [5]:
pop0.oud_consistent.value_counts()

susceptible_to_oud_consistent      97573
oud_consistent                      1915
on_treatment_for_oud_consistent      512
Name: oud_consistent, dtype: int64

In [6]:
pop0.quarters.value_counts()

housed    100000
Name: quarters, dtype: int64

In [7]:
sim.take_steps(10)

VBox(children=(HTML(value=''), IntProgress(value=0, max=10)))

/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(

In [8]:
pop1 = sim.get_population()

In [9]:
pop1.oud_consistent.value_counts()

susceptible_to_oud_consistent      97577
oud_consistent                      1906
on_treatment_for_oud_consistent      517
Name: oud_consistent, dtype: int64

In [10]:
pop1.quarters.value_counts()

housed          99537
incarcerated      246
unhoused          217
Name: quarters, dtype: int64

In [11]:
pd.crosstab(pop0.oud_consistent, pop0.quarters, margins=True)

quarters                         housed     All
oud_consistent
on_treatment_for_oud_consistent     512     512
oud_consistent                     1915    1915
susceptible_to_oud_consistent     97573   97573
All                              100000  100000

In [12]:
np.round(100*pd.crosstab(pop1.oud_consistent, pop1.quarters, margins=True, normalize='index'), 1)

quarters                         housed  incarcerated  unhoused
oud_consistent
on_treatment_for_oud_consistent    99.4           0.4       0.2
oud_consistent                     99.5           0.3       0.3
susceptible_to_oud_consistent      99.5           0.2       0.2
All                                99.5           0.2       0.2

In [13]:
np.round(100*pd.crosstab(pop1.quarters, pop1.oud_consistent, margins=True, normalize='index'), 1)

oud_consistent,on_treatment_for_oud_consistent,oud_consistent,susceptible_to_oud_consistent
quarters,,,
housed,0.5,1.9,97.6
incarcerated,0.8,2.0,97.2
unhoused,0.5,2.3,97.2
All,0.5,1.9,97.6

# Goal: induce corelation between quarters and oud state

Approach: follow pattern similar to the Risk and RiskEffect models.

In [14]:
sim.step()

/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(
/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/vivarium/framework/lookup/interpolation.py:114: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  sub_tables = list(

In [15]:
pop2 = sim.get_population()

In [16]:
t = pd.concat([pop0, pop1, pop2], axis=1).filter(like='quarters')
t[t.iloc[:, 2] != 'housed']

,quarters,previous_quarters,quarters,previous_quarters,quarters,previous_quarters
417,housed,housed,incarcerated,housed,incarcerated,incarcerated
684,housed,housed,incarcerated,incarcerated,incarcerated,incarcerated
800,housed,housed,unhoused,unhoused,unhoused,unhoused
1197,housed,housed,unhoused,unhoused,unhoused,unhoused
1252,housed,housed,incarcerated,incarcerated,incarcerated,incarcerated
...,...,...,...,...,...,...
97949,housed,housed,incarcerated,incarcerated,incarcerated,incarcerated
98413,housed,housed,unhoused,unhoused,unhoused,unhoused
98908,housed,housed,unhoused,unhoused,unhoused,unhoused
99050,housed,housed,incarcerated,incarcerated,incarcerated,incarcerated
99937,housed,housed,unhoused,unhoused,unhoused,unhoused

In [17]:
[x for x in sim.list_values() if 'expo' in x]

['quarters_risk.exposure']

In [26]:
%cd /home/abie/vivarium_results/washington/2025_05_06_00_22_12/results
!ls -halt

/home/abie/vivarium_results/washington/2025_05_06_00_22_12/results
total 72K
drwxrwxr-x 2 abie abie 4.0K May  6 01:35 .
drwxrwxr-x 3 abie abie 4.0K May  6 01:35 ..
-rw-rw-r-- 1 abie abie 5.9K May  6 01:35 deaths.parquet
-rw-rw-r-- 1 abie abie 5.9K May  6 01:35 ylls.parquet
-rw-rw-r-- 1 abie abie 7.6K May  6 01:35 transition_count_quarters.parquet
-rw-rw-r-- 1 abie abie 7.0K May  6 01:35 transition_count_oud_consistent.parquet
-rw-rw-r-- 1 abie abie 8.2K May  6 01:35 person_time_oud_consistent.parquet
-rw-rw-r-- 1 abie abie 8.2K May  6 01:35 person_time_quarters.parquet
-rw-rw-r-- 1 abie abie 6.1K May  6 01:35 ylds.parquet

/home/abie/miniforge3/envs/vivarium_nih_moud_simulation/lib/python3.11/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [19]:
# pd.read_parquet('deaths.parquet').sort_values('value', ascending=False)

In [20]:
# pd.read_parquet('ylls.parquet').sort_values('value', ascending=False)

In [31]:
df_t = pd.read_parquet('transition_count_oud_consistent.parquet').sort_values('value')
df_t

,measure,entity_type,entity,sub_entity,age_group,current_year,sex,quarters,value
0,transition_count,cause,oud_consistent,susceptible_to_oud_consistent_to_oud_consistent,early_neonatal,2019,Female,housed,0.0
1019,transition_count,cause,oud_consistent,on_treatment_for_oud_consistent_to_susceptible...,55_to_59,2020,Male,incarcerated,0.0
1018,transition_count,cause,oud_consistent,on_treatment_for_oud_consistent_to_susceptible...,55_to_59,2020,Male,unhoused,0.0
1017,transition_count,cause,oud_consistent,on_treatment_for_oud_consistent_to_susceptible...,55_to_59,2020,Male,housed,0.0
1016,transition_count,cause,oud_consistent,on_treatment_for_oud_consistent_to_oud_consistent,55_to_59,2020,Male,incarcerated,0.0
...,...,...,...,...,...,...,...,...,...
609,transition_count,cause,oud_consistent,on_treatment_for_oud_consistent_to_oud_consistent,25_to_29,2019,Female,housed,74.0
729,transition_count,cause,oud_consistent,on_treatment_for_oud_consistent_to_oud_consistent,35_to_39,2019,Female,housed,79.0
666,transition_count,cause,oud_consistent,oud_consistent_to_on_treatment_for_oud_consistent,30_to_34,2019,Female,housed,86.0
606,transition_count,cause,oud_consistent,oud_consistent_to_on_treatment_for_oud_consistent,25_to_29,2019,Female,housed,94.0
621,transition_count,cause,oud_consistent,oud_consistent_to_on_treatment_for_oud_consistent,25_to_29,2019,Male,housed,103.0

In [32]:
df_t[df_t.sub_entity == 'oud_consistent_to_on_treatment_for_oud_consistent'].groupby('quarters').sum()

/tmp/ipykernel_159129/346323945.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_t[df_t.sub_entity == 'oud_consistent_to_on_treatment_for_oud_consistent'].groupby('quarters').sum()

              value
quarters
housed        574.0
incarcerated  107.0
unhoused        1.0

In [22]:
# pd.read_parquet('transition_count_quarters.parquet').sort_values('value')

In [30]:
df_pt = pd.read_parquet('person_time_quarters.parquet').sort_values('value')
df_pt

,measure,entity_type,entity,sub_entity,age_group,current_year,sex,oud_consistent,value
899,person_time,cause,quarters,incarcerated,95_plus,2020,Male,on_treatment_for_oud_consistent,0.000000
764,person_time,cause,quarters,incarcerated,80_to_84,2019,Female,on_treatment_for_oud_consistent,0.000000
763,person_time,cause,quarters,unhoused,80_to_84,2019,Female,on_treatment_for_oud_consistent,0.000000
762,person_time,cause,quarters,housed,80_to_84,2019,Female,on_treatment_for_oud_consistent,0.000000
761,person_time,cause,quarters,incarcerated,80_to_84,2019,Female,oud_consistent,0.000000
...,...,...,...,...,...,...,...,...,...
396,person_time,cause,quarters,housed,30_to_34,2019,Female,susceptible_to_oud_consistent,4810.135524
405,person_time,cause,quarters,housed,30_to_34,2019,Male,susceptible_to_oud_consistent,4822.858316
432,person_time,cause,quarters,housed,35_to_39,2019,Female,susceptible_to_oud_consistent,4896.000000
441,person_time,cause,quarters,housed,35_to_39,2019,Male,susceptible_to_oud_consistent,4897.483915
261,person_time,cause,quarters,housed,10_to_14,2019,Male,susceptible_to_oud_consistent,4899.315537

In [33]:
df_pt[df_pt.oud_consistent == 'oud_consistent'].groupby('sub_entity').sum()

/tmp/ipykernel_159129/28522647.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_pt[df_pt.oud_consistent == 'oud_consistent'].groupby('sub_entity').sum()

                    value
sub_entity
housed        1743.553730
incarcerated    38.603696
unhoused        64.312115

In [35]:
(
    df_t[df_t.sub_entity == 'oud_consistent_to_on_treatment_for_oud_consistent'].groupby('quarters').sum()
    /
    df_pt[df_pt.oud_consistent == 'oud_consistent'].groupby('sub_entity').sum()
)

/tmp/ipykernel_159129/4195153207.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_t[df_t.sub_entity == 'oud_consistent_to_on_treatment_for_oud_consistent'].groupby('quarters').sum()
/tmp/ipykernel_159129/4195153207.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_pt[df_pt.oud_consistent == 'oud_consistent'].groupby('sub_entity').sum()

                 value
quarters
housed        0.329213
incarcerated  2.771755
unhoused      0.015549

In [24]:
# pd.read_parquet('person_time_oud_consistent.parquet').sort_values('value')

In [25]:
# pd.read_parquet('ylds.parquet').sort_values('value')